from typing import Any, Callable, Protocol, Self, runtime_checkable

from src.application.common.interfaces.usecase import UseCase, UseCaseType
from src.application.common.request import Request


@runtime_checkable
class Mediator(Protocol):
    async def send[Q: Request, R](self, request: Q) -> R: ...
    def register[Q: Request](
        self, request: type[Q], use_case: type[UseCaseType]
    ) -> None: ...
    def build(self) -> Self: ...
    def dependencies(self, **dependencies: Any) -> Self: ...
    def use_cases(self, *use_cases_factory: Callable[[Self], None]) -> Self: ...
    @classmethod
    def builder(cls) -> Self: ...
    def _get_use_case[Q: Request, R](self, request: Q) -> UseCase[Q, R]: ...
