from typing import Any, Callable, Protocol, Self, runtime_checkable

from src.api.common.dto.base import DTO
from src.api.common.interfaces.handler import Handler, HandlerType


@runtime_checkable
class Mediator(Protocol):
    async def send[Q: DTO, R: DTO](self, query: Q) -> R: ...
    def register[Q: DTO](self, query: type[Q], handler: type[HandlerType]) -> None: ...
    def build(self) -> Self: ...
    def middleware(self) -> Self: ...
    def dependencies(self, **dependencies: Any) -> Self: ...
    def handlers(self, *handlers_factory: Callable[[Self], None]) -> Self: ...
    @classmethod
    def builder(cls) -> Self: ...
    def _get_handler[Q: DTO, R: DTO](self, query: Q) -> Handler[Q, R]: ...
