from datetime import timedelta
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Cache[K, R](Protocol):
    async def exists(self, key: K) -> bool: ...
    async def get(self, key: K) -> R | None: ...
    # expire in seconds or delta
    async def set(
        self, key: K, value: Any, expire: float | timedelta | None = None, **kw: Any
    ) -> None: ...
    async def delete(self, *keys: K) -> None: ...
    async def get_list(
        self,
        key: K,
    ) -> list[R]: ...
    # expire in seconds or delta
    async def set_list(
        self, key: K, *values: Any, expire: float | timedelta | None = None, **kw: Any
    ) -> None: ...
    async def discard(
        self,
        key: K,
        value: Any,
        **kw: Any,
    ) -> bool: ...
    async def keys(self, pattern: K | None = None) -> list[K]: ...
    async def clear(self) -> None: ...
    async def close(self) -> None: ...


@runtime_checkable
class StrCache(Cache[str, str], Protocol): ...
