from abc import ABC, abstractmethod
from typing import Optional, Protocol, runtime_checkable


class ConnectionPool(ABC):
    @abstractmethod
    async def acquire(self) -> Optional[str]: ...

    @abstractmethod
    async def release(self, connection_id: str) -> bool: ...


@runtime_checkable
class ProxyPoolMapper[K, V](Protocol):
    @property
    def proxies(self) -> list[K]: ...

    def load_proxies(self, proxies: list[K]) -> None: ...

    def bind(self, proxy: K, item: V) -> None: ...

    def unbind(self, proxy: K, item: V) -> bool: ...

    def unbind_all(self, proxy: K) -> None: ...

    def remove_proxy(self, proxy: K) -> None: ...

    def get_bound_items(self, proxy: K) -> list[V] | None: ...

    def count_bound_items(self, proxy: K) -> int: ...

    def find_proxy_for(self, item: V) -> K | None: ...

    def close(self) -> None: ...


@runtime_checkable
class AsyncProxyPoolMapper[K, V](Protocol):
    @property
    async def proxies(self) -> list[K]: ...

    async def load_proxies(self, proxies: list[K]) -> None: ...

    async def bind(self, proxy: K, item: V) -> None: ...

    async def unbind(self, proxy: K, item: V) -> bool: ...

    async def unbind_all(self, proxy: K) -> None: ...

    async def remove_proxy(self, proxy: K) -> None: ...

    async def get_bound_items(self, proxy: K) -> list[V] | None: ...

    async def count_bound_items(self, proxy: K) -> int: ...

    async def find_proxy_for(self, item: V) -> K | None: ...

    async def get_proxies_with_counts(self) -> dict[K, int]: ...

    async def close(self) -> None: ...
